### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by alexkdeveloper** [comment]
Hi!
Po files are needed. pot files are templates from which po files are created.  The error occurs in GitHub actions without po files. Because the corresponding nl.po file was not found, as indicated in LINGUAS.
It was also in BMI. 
Here is what is output in Actions:
msgfmt: error while opening "nl.po" for reading: No such file or directory

**Comment by Vistaus** [comment]
Yes, I noticed my mistake. Sorry 'bout that! I'm in the process of switching from Poedit to Lokalize and Lokalize seems to have a bit of a different workflow. I'll correct this issue ASAP!

**Comment by Vistaus** [comment]
Should be corrected now. 🙂 (also for BMI)

**Comment by alexkdeveloper** [comment]
Thanks)))

**Pull request merged**
