### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by alexkdeveloper**

### CODE REVIEW

**Comment by ryonakano** [comment]
I'm AFK so will check this PR later.

**Comment by ryonakano** [comment]
Looks good, but I personally think we could keep the icons symbolic ones. Other apps on elementary seem to use symbolic ones for `Gtk.Entry`.

**Comment by alexkdeveloper** [comment]
Yes, I agree. We can use symbolic icons for Entry.

**Comment by alexkdeveloper** [comment]
I changed the icons in the Entry. I changed the label on the button from "Edit" to "Show All".

**Comment by alexkdeveloper** [comment]
Hi! Workflows have been added. I checked flatpack on my computer. Everything works! How do you like this app?

**Comment by ryonakano** [comment]
Yes, looks even better than current `master`!

**Comment by alexkdeveloper** [comment]
Do you think it's worth trying to publish in the App Center?

**Comment by ryonakano** [comment]
Yes! But I suppose you're using an app icon brought from other apps (Winaero?) If so, you should prepare an unique icon before publishing.

**Comment by alexkdeveloper** [comment]
I took the icon from here:
https://v1.iconsearch.ru/detailed/28918/6/
The license is specified by the LGPL

**Pull request merged**
